export const ORDER_LIST_SERVER_URL: 'wss://norma.nomoreparties.space/orders/all' = 'wss://norma.nomoreparties.space/orders/all';
export const ORDER_LIST_AUTH_SERVER_URL: 'wss://norma.nomoreparties.space/orders' = 'wss://norma.nomoreparties.space/orders';

export const AUTH_REGISTER: 'AUTH_REGISTER' = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS' = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILED: 'AUTH_REGISTER_FAILED' = 'AUTH_REGISTER_FAILED';
export const AUTH_LOGIN: 'AUTH_LOGIN' = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS' = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED' = 'AUTH_LOGIN_FAILED';
export const AUTH_TOKEN: 'AUTH_TOKEN' = 'AUTH_TOKEN';
export const AUTH_TOKEN_SUCCESS: 'AUTH_TOKEN_SUCCESS' = 'AUTH_TOKEN_SUCCESS';
export const AUTH_TOKEN_FAILED: 'AUTH_TOKEN_FAILED' = 'AUTH_TOKEN_FAILED';
export const AUTH_LOGOUT: 'AUTH_LOGOUT' = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS' = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILED: 'AUTH_LOGOUT_FAILED' = 'AUTH_LOGOUT_FAILED';
export const AUTH_LOAD_USER: 'AUTH_LOAD_USER' = 'AUTH_LOAD_USER';
export const AUTH_LOAD_USER_SUCCESS: 'AUTH_LOAD_USER_SUCCESS' = 'AUTH_LOAD_USER_SUCCESS';
export const AUTH_LOAD_USER_FAILED: 'AUTH_LOAD_USER_FAILED' = 'AUTH_LOAD_USER_FAILED';
export const AUTH_UPDATE_USER: 'AUTH_UPDATE_USER' = 'AUTH_UPDATE_USER';
export const AUTH_UPDATE_USER_SUCCESS: 'AUTH_UPDATE_USER_SUCCESS' = 'AUTH_UPDATE_USER_SUCCESS';
export const AUTH_UPDATE_USER_FAILED: 'AUTH_UPDATE_USER_FAILED' = 'AUTH_UPDATE_USER_FAILED';

export const CONSTRUCTOR_ADD_INGREDIENT: 'CONSTRUCTOR_ADD_INGREDIENT' = 'CONSTRUCTOR_ADD_INGREDIENT';
export const CONSTRUCTOR_ADD_BUN: 'CONSTRUCTOR_ADD_BUN' = 'CONSTRUCTOR_ADD_BUN';
export const CONSTRUCTOR_COUNT_TOTAL_PRICE: 'CONSTRUCTOR_COUNT_TOTAL_PRICE' = 'CONSTRUCTOR_COUNT_TOTAL_PRICE';
export const CONSTRUCTOR_REMOVE_INGREDIENT: 'CONSTRUCTOR_REMOVE_INGREDIENT' = 'CONSTRUCTOR_REMOVE_INGREDIENT';
export const CONSTRUCTOR_SORT_INGREDIENT: 'CONSTRUCTOR_SORT_INGREDIENT' = 'CONSTRUCTOR_SORT_INGREDIENT';

export const GET_INGREDIENTS: 'GET_INGREDIENTS' = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';

export const ORDER_SEND: 'ORDER_SEND' = 'ORDER_SEND';
export const ORDER_SEND_FAILED: 'ORDER_SEND_FAILED' = 'ORDER_SEND_FAILED';
export const ORDER_SEND_SUCCESS: 'ORDER_SEND_SUCCESS' = 'ORDER_SEND_SUCCESS';
export const ORDER_SEND_CLOSE: 'ORDER_SEND_CLOSE' = 'ORDER_SEND_CLOSE';

export const ORDER_LIST_CONNECT: 'ORDER_LIST_CONNECT' = 'ORDER_LIST_CONNECT';
export const ORDER_LIST_DISCONNECT: 'ORDER_LIST_DISCONNECT' = 'ORDER_LIST_DISCONNECT';
export const ORDER_LIST_WS_SUCCESS: 'ORDER_LIST_WS_SUCCESS' = 'ORDER_LIST_WS_SUCCESS';
export const ORDER_LIST_WS_CLOSE: 'ORDER_LIST_WS_CLOSE' = 'ORDER_LIST_WS_CLOSE';
export const ORDER_LIST_WS_MESSAGE: 'ORDER_LIST_WS_MESSAGE' = 'ORDER_LIST_WS_MESSAGE';
export const ORDER_LIST_WS_ERROR: 'ORDER_LIST_WS_ERROR' = 'ORDER_LIST_WS_ERROR';